# Generated by Django 2.1.5 on 2019-01-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upassword', models.CharField(max_length=20)),
                ('upriority', models.IntegerField()),
                ('unickname', models.CharField(max_length=20)),
            ],
        ),
    ]
